test = {   'name': 'q1_c',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> round(reg_data.loc["Afghanistan", "fitted_slr"], 5) == 4.60644\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> round(reg_data.loc["Afghanistan", "resid_slr"], 5) == -0.13344\nTrue', 'hidden': False, 'locked': False},
                                   {'code': ">>> (reg_data['fitted_slr'] == fitted_slr).all()\nTrue", 'hidden': True, 'locked': False},
                                   {'code': ">>> (reg_data['resid_slr'] == resid_slr).all()\nTrue", 'hidden': True, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
