test = {   'name': 'q1_a',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': ">>> round(pca_var_explained.loc[(pca_var_explained.Component == 3), 'Cumulative variance explained'], 1).values[0] == 0.5\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> round(pca_var_explained.loc[(pca_var_explained.Component == 3), 'Proportion of variance explained'], 1).values[0] == 0.1\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
